# compass_perf/data_loader.py

"""
Helpers for discovering and loading DICOM files from disk.

Designed for:
- Synthetic datasets generated by DVTK/DCMTK
- Anonymized clinical datasets
as described in the test plan.

Note: This module evolved from the earlier cataloging approach used in 0_dcm_read_studyids.py,
which was used to understand dataset structure before building the performance testing suite.
This module focuses on efficient file discovery and loading for performance testing, while
the original script remains useful for detailed metadata cataloging and analysis.
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterable, List

import pydicom


def is_dicom_file(path: Path) -> bool:
    """
    Check if a file is a valid DICOM file by verifying the DICOM magic string.
    
    DICOM files have a 128-byte preamble followed by the 'DICM' magic string.
    This function performs a quick check without fully parsing the file.
    
    Args:
        path: Path to the file to check
        
    Returns:
        True if the file has the DICOM magic string, False otherwise
    """
    try:
        with open(path, 'rb') as f:
            f.seek(128)  # Skip to byte 128 (end of preamble)
            magic = f.read(4)  # Read 4 bytes for 'DICM'
            return magic == b'DICM'
    except (IOError, OSError):
        # File can't be read or is too small
        return False


def find_dicom_files(root: Path, recursive: bool = True) -> List[Path]:
    """
    Find DICOM files under the given root directory.
    
    This function validates each file to ensure it contains the DICOM magic string
    before including it in the results. This prevents non-DICOM files from being
    processed, regardless of their file extension.
    
    Note: Supports DICOM files with any extension or no extension at all,
    as DICOM files are identified by their internal structure, not filename.
    """
    if not root.exists():
        raise FileNotFoundError(f"DICOM root directory does not exist: {root}")

    pattern = "**/*" if recursive else "*"
    files: List[Path] = []
    for path in root.glob(pattern):
        if not path.is_file():
            continue

        if path.name.startswith("."):
            continue

        # Validate that the file is actually a DICOM file
        if not is_dicom_file(path):
            continue

        files.append(path)

    if not files:
        raise RuntimeError(f"No DICOM files found under: {root}")

    return sorted(files)


def load_dataset(path: Path):
    """
    Load a DICOM dataset for sending.

    pydicom is used only to parse and validate the file.
    Pixel data is kept in memory by default (needed for C-STORE).
    """
    return pydicom.dcmread(path, force=True)


def iter_datasets(paths: Iterable[Path]):
    """
    Convenience generator: yields (path, dataset) pairs.

    We keep reading in the test process so that malformed headers / missing tags
    are detected before we hit the network (matches "Synthetic Data" strategy).
    """
    for path in paths:
        ds = load_dataset(path)
        yield path, ds
