# compass_perf/data_loader.py

"""
Helpers for discovering and loading DICOM files from disk.

Designed for:
- Synthetic datasets generated by DVTK/DCMTK
- Anonymized clinical datasets
as described in the test plan.
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterable, List

import pydicom


def find_dicom_files(root: Path, recursive: bool = True) -> List[Path]:
    """
    Find DICOM files under the given root directory.

    We keep this simple and assume: "one file per dataset",
    using the production-style .dcm layout.
    """
    if not root.exists():
        raise FileNotFoundError(f"DICOM root directory does not exist: {root}")

    pattern = "**/*" if recursive else "*"
    files: List[Path] = []
    for path in root.glob(pattern):
        if not path.is_file():
            continue

        if path.name.startswith("."):
            continue

        files.append(path)

    if not files:
        raise RuntimeError(f"No DICOM files found under: {root}")

    return sorted(files)


def load_dataset(path: Path):
    """
    Load a DICOM dataset for sending.

    pydicom is used only to parse and validate the file.
    Pixel data is kept in memory by default (needed for C-STORE).
    """
    return pydicom.dcmread(path, force=True)


def iter_datasets(paths: Iterable[Path]):
    """
    Convenience generator: yields (path, dataset) pairs.

    We keep reading in the test process so that malformed headers / missing tags
    are detected before we hit the network (matches "Synthetic Data" strategy).
    """
    for path in paths:
        ds = load_dataset(path)
        yield path, ds
